In [21]:
import pandas as pd
import numpy as np

In [24]:
df = pd.DataFrame(data={
    'col1':[1,2,3,4,5],
    'col2':[6,7,8,9,10],
    'col3':['a','b','c','d','e']
}, index = [1,3,5,7,9])
df.index

Index([1, 3, 5, 7, 9], dtype='int64')

In [26]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [28]:
df.values

array([[1, 6, 'a'],
       [2, 7, 'b'],
       [3, 8, 'c'],
       [4, 9, 'd'],
       [5, 10, 'e']], dtype=object)

In [29]:
df

col1  col2 col3
1     1     6    a
3     2     7    b
5     3     8    c
7     4     9    d
9     5    10    e

In [30]:
df.loc[1]

col1    1
col2    6
col3    a
Name: 1, dtype: object

In [ ]:
index = [1,3,5,7,9]に「2」が存在しないため、これはエラーになる

In [33]:
df.loc[2]

KeyError: 2

In [ ]:
### なぜ列にアクセスできない？
覚え方：
df.loc[行, 列] - 行と列の両方を指定
df['列名'] - 列のみを指定
df.loc['行名'] - 行のみを指定

In [34]:
df.loc['col1']

KeyError: 'col1'

In [35]:
df['col1']

1    1
3    2
5    3
7    4
9    5
Name: col1, dtype: int64

### なぜ行にだけloc関数が必要？
DataFrameでは「列を取り出す」操作が最も頻繁
だからdf['列名']というショートカットが用意されている
行の取り出しは相対的に少ないので、明示的にlocを使う設計

In [36]:
df.loc[[1,3], ['col1','col3']]

col1 col3
1     1    a
3     2    b

In [37]:
df

col1  col2 col3
1     1     6    a
3     2     7    b
5     3     8    c
7     4     9    d
9     5    10    e

In [38]:
df.loc[[1,3], :]

col1  col2 col3
1     1     6    a
3     2     7    b

In [39]:
df.loc[[1], ['col1']]

col1
1     1

In [40]:
df[[:], ['col3']]

SyntaxError: invalid syntax (ipython-input-40-3950296969.py, line 1)

### これはなぜダメ？ df[[:], ['col3']]

df[] の中は列の指定のみ
[:] はスライス記法でリスト内では使えない
df[] に複数の引数は渡せない

覚え方：
df[] = 列専用
df.loc[] = 行・列両方OK


In [42]:
# これなら指定した列だけ出力できる
df['col3']

1    a
3    b
5    c
7    d
9    e
Name: col3, dtype: object

# numpyの練習

In [49]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [48]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
a.shape

(3,)

In [51]:
a.dtype

dtype('int64')

In [53]:
a = np.arange(0, 30, 5)
a

array([ 0,  5, 10, 15, 20, 25])

### numpyでDataFrameを作る

In [55]:
df = pd.DataFrame(np.arange(0,30,5))
df

0
0   0
1   5
2  10
3  15
4  20
5  25

In [57]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])